language: haskell
ghc: 7.8
before_install:
- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install --force-yes cabal-install-1.22 happy-1.19.3 alex-3.1.3
- export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:/opt/cabal/1.22/bin:$PATH
- git clone https://github.com/sneerteam/sneer.git --depth 1 --branch master --single-branch sneer
install:
- cabal update
- cabal install cabal-install
- cabal --version
before_script:
- sneer/gradlew --build-file sneer/build.gradle -q :server:run -Pserver-options="[5555, 8282]" &
- sleep 5
script:
- cabal --version
- cabal sandbox init
- cabal install --only-dependencies --enable-tests -j2 --allow-newer
- cabal check
- cabal configure --enable-tests
- cabal build
- cabal test --show-details=always --test-options="--color"
